name: "Terraform Destroy"
on: workflow_dispatch
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  actions: read
  security-events: write

jobs:
  plan_destroy:
    name: "Terraform Plan Destroy"
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID_DEV}}:role/${{vars.ROLE_NAME}}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Replace AWS region in providers.tf
        run: sed -i.tmp "s/AWSREGION/${{vars.AWS_REGION}}/g" ./infrastructure/providers.tf
      - name: Download Terraform
        uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=./infrastructure init -backend-config=./backend.hcl
      - name: Terraform Plan Destroy
        run: terraform -chdir=./infrastructure plan -destroy -var-file=environments/development.tfvars -out=development-destroy.tfplan
      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./infrastructure/development-destroy.tfplan
  apply_destroy:
    name: "Terraform Apply Destroy"
    needs: [plan_destroy]
    runs-on: ubuntu-latest
    environment: development_destroy
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID_DEV}}:role/${{vars.ROLE_NAME}}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
      - run: ls -al
      - run: pwd
      - run: ls -al ./infrastructure
      - name: Replace AWS region in providers.tf
        run: sed -i.tmp "s/AWSREGION/${{vars.AWS_REGION}}/g" ./infrastructure/providers.tf
      - name: Download Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=./infrastructure init -backend-config=./backend.hcl
      - name: Terraform Apply  Destroy
        run: terraform -chdir="./infrastructure" apply "../development-destroy.tfplan"
